### ISSUE TITLE
The Start Game Problem

### ISSUE THREAD

**Issue by StefanBETA2008** [MAJigsaw77/FNF-Chain-Saw-Engine#2]
I Can't Start Your Engine:

https://user-images.githubusercontent.com/109828559/190718226-047d00ba-ce99-4b54-b32e-626a3091c47d.mp4

**Comment by StefanBETA2008** [comment]
Sorry For The Video.

**Comment by StefanBETA2008** [comment]
https://user-images.githubusercontent.com/109828559/190718443-851ce369-3523-4dd7-9a8d-0a5580e9b06e.mp4

Here's Better

**Comment by MAJigsaw77** [comment]
Phone issue

**Comment by StefanBETA2008** [comment]
> Phone issue

Really? I Saw When I Just Added The Sdk Version On My Engine To Project.xml, It's Closing Automatically.

**Comment by MAJigsaw77** [comment]
-_-

**Comment by StefanBETA2008** [comment]
I Have 4GB Of Ram
