### ISSUE TITLE
The Problem #2

### ISSUE THREAD

**Issue by StefanBETA2008** [MAJigsaw77/FNF-Chain-Saw-Engine#4]
This It's What I Got:
![Screenshot_20220923-123221](https://user-images.githubusercontent.com/109828559/191966988-27c4606b-6c49-4484-a48c-47d9eb2ad3ba.png)
`states/ModsMenuState.hx (line 119)
states/ModsMenuState.hx (line 57)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
Null Object Reference`
I Just Pressed The Button C And This It's What Happened.
![Screenshot_20220923-123534](https://user-images.githubusercontent.com/109828559/191967063-44459745-26ac-41d7-84fb-4ea682819e7d.png)
`/opt/hostedtoolcache/haxe/4.2.5/x64/std/haxe/format/JsonParser.hx (line 318)
/opt/hostedtoolcache/haxe/4.2.5/x64/std/haxe/format/JsonParser.hx (line 147)
/opt/hostedtoolcache/haxe/4.2.5/x64/std/haxe/format/JsonParser.hx (line 57)
parsers/Stage.hx (line 28)
parsers/Stage.hx (line 19)
states/PlayState.hx (line 154)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
Invalid char 0 at position 0`
And This It's When I Just Pressed Week 7 Song's.

**Comment by BushTrain460615** [comment]
@MAJigsaw77 you know android stuff

**Comment by MAJigsaw77** [comment]
These errors happens even in pc

**Comment by MAJigsaw77** [comment]
I'll have to fix them

**Comment by StefanBETA2008** [comment]
Good Luck To Fixing It.

**Comment by StefanBETA2008** [comment]
I Will Close The Issue...

**Comment by StefanBETA2008** [comment]
![Screenshot_20220927-022016](https://user-images.githubusercontent.com/109828559/192403322-7de3e130-dfe9-4324-889e-13cab6c5e3bb.png)
Really?
'/opt/hostedtoolcache/haxe/4.2.5/x64/std/haxe/format/JsonParser.hx (line 318)
/opt/hostedtoolcache/haxe/4.2.5/x64/std/haxe/format/JsonParser.hx (line 147)
/opt/hostedtoolcache/haxe/4.2.5/x64/std/haxe/format/JsonParser.hx (line 57)
parsers/Character.hx (line 43)
parsers/Character.hx (line 34)
Character.hx (line 36)
states/PlayState.hx (line 190)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)
Invalid char 0 at position 0'
Are You Charted All Week7 Song's?

**Comment by MAJigsaw77** [comment]
I didn't finish week 7 in my engine

**Comment by StefanBETA2008** [comment]
> I didn't finish week 7 in my engine

Oh, Okay. Sorry MAJigsaw77. I Didn't Know
